minimumReleaseAgeExclude:
  - '@alwaysmeticulous/api@2.290.0'
  - '@alwaysmeticulous/client@2.290.0'
  - '@alwaysmeticulous/custom-checks@2.290.1'
  - '@alwaysmeticulous/downloading-helpers@2.290.0'
  - '@alwaysmeticulous/api@2.300.0'
  - '@alwaysmeticulous/client@2.300.0'
  - '@alwaysmeticulous/common@2.300.0'
  - '@alwaysmeticulous/custom-checks@2.300.0'
  - '@alwaysmeticulous/downloading-helpers@2.300.0'
